site_name: BRT Documentation
site_url: https://grupodiana.github.io/BRT-Documentation/
site_author: Diana Research Group - University of Malaga
site_description: Documentation site of the entire BRT ecosystem

repo_name: GrupoDiana/BRTLibrary
repo_url: https://github.com/GrupoDiana/BRTLibrary
edit_uri: ""

copyright: Copyright &copy; 2024 <a href="https://www.diana.uma.es/" target="_blank" rel="noopener"> Diana Research Group</a>

theme:
  name: material
  custom_dir: docs/custom_theme
  features:
  - navigation.indexes
  #- navigation.sections
  - navigation.tabs  
  - navigation.top  
  - navigation.tracking
  - navigation.path  
  - toc.integrate
  - toc.follow
  - search.suggest
  - search.highlight
  - content.tabs.link
  - content.code.annotation
  - content.code.copy
  logo: assets/logos/SONICOMwave.png
  favicon: assets/logos/SONICOMwave.png
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: pink
      accent: green
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: pink
      accent: lime

markdown_extensions:
  - toc:
      toc_depth: 3
  - pymdownx.tabbed
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js  

extra_css:
  - https://unpkg.com/katex@0/dist/katex.min.css



plugins:
    - with-pdf:
        author: Diana Research Group - University of Malaga
        copyright:  This document - Copyright &copy; 2024 Diana Research Group
        #
        cover: true        
        cover_title: Binaural Rendering Toolbox (BRT)
        cover_subtitle: Technical documentation
        cover_logo:  assets/logos/sonicom_logo.png
        #back_cover: true
        #custom_template_path: templates
        #
        #toc_title: TOC TITLE TEXT
        #heading_shift: false
        toc_level: 3
        #ordered_chapter_level: 2
        #excludes_children:
        #    - 'release-notes/:upgrading'
        #    - 'release-notes/:changelog'
        #
        #exclude_pages:
        #    - 'bugs/'
        #    - 'appendix/contribute/'
        #convert_iframe:
        #    - src: IFRAME SRC
        #      img: POSTER IMAGE URL
        #      text: ALTERNATE TEXT
        #    - src: ...
        two_columns_level: 3
        #
        #render_js: true
        #headless_chrome_path: headless-chromium
        #
        output_path: assets/brt-documentation.pdf
        enabled_if_env: ENABLE_PDF_EXPORT              #commnent this line to enable the plugin in local builds
        #
        #debug_html: true
        #show_anchors: true
        #verbose: true
        
# Page tree
nav:
  - Home: index.md
  - BRT Library: 
    - library/index.md
    
    - Source Models: 
      - library/source-models/index.md
      - Omnidirectional Model: library/source-models/simple-omnidirectional-source-model.md
      - Directivity Model: library/source-models/directivity-source-model.md
      - Virtual Source Model: library/source-models/virtual-source-model.md
    - Listener Models: 
      - library/listener-models/index.md
      - HRTF Models:
        - library/listener-models/hrtf-models/index.md
        - Direct HRTF Convolution: library/listener-models/hrtf-models/listener-acoustic-model-hrtf.md
        - Ambisonic HRTF Convoution model: library/listener-models/hrtf-models/listener-acoustic-model-ambisonic-hrtf.md
      - RIR models: 
        - library/listener-models/rir-models/index.md                
        - Direct BRIR Convolution Model:  library/listener-models/rir-models/listener-acoustic-environment-model-brir.md      
        - Ambisoninc BRIR Convolution Model: library/listener-models/rir-models/listener-acoustic-environment-model-ambisonic-brir.md
    - Environment Models:
      - library/environment-models/index.md   
      - Free Field Model: library/environment-models/freefield-environment-model.md   
      - SDN Model: library/environment-models/sdn-environment-model.md
    - Binaural Filters:
      - library/binaural-filters/index.md
    - Services Modules: 
      - library/service-modules/index.md
      - HRTF: library/service-modules/service-hrtf.md
      - BRIR: library/service-modules/service-hrbrir.md
      - Directivity TF: library/service-modules/service-directivity-tf.md
      - SOS Filters: library/service-modules/service-sos-filters.md
      - AmbisonicBIR: library/service-modules/service-ambisonic-bir.md    
    - SOFA Readers: 
      - library/readers/index.md            
    - Infrastructure Entities:
      - library/infrastructure-entities/index.md
      - Processing Modules: 
        - library/processing-modules/index.md
       # - Ambisonic Encoder: library/processing-modules/ambisonic-encoder.md
        - Ambisonic Domain Convolver: library/processing-modules/ambisonic-domain-convolver.md
        - Bilateral Ambisonic Encoder: library/processing-modules/bilateral-ambisonic-encoder.md
        - Uniform Partitioned Convolution: library/processing-modules/uniform-partitioned-convolution.md    
      - Common:
        - library/common/index.md
      #- Base:
      #  - library/base/index.md
      #- Connectivity: 
      #  - library/connectivity/index.md
      
  - Applications: 
    - applications/index.md
    - BeRTA Rendeder: 
      - applications/berta-renderer/index.md      
    - BeRTA GUI: applications/berta-gui.md
    - OSC Commands: 
      - osc/index.md
      - Control commands: osc/control.md
      - Overall commands: osc/overall.md
      - Resources commands: osc/resources.md
      - Source commands: osc/source.md
      - Listener commands: osc/listener.md
      - Environment commands: osc/environment.md
      - Binaural Filter commands: osc/binaural-filter.md
    - Unity OSC Package: applications/unity-osc-package.md
    - Settings File: applications/settingsFile.md
    - Annotated Receiver Audio: applications/annotated-audio.md
    - Calibration: applications/calibration.md
    - Safety Limiter: applications/safety-limiter.md
  #- Examples: 
   # - Code blocks: example-code.md    
   # - Icons: example-emoji.md
    
