site_name: BRT Documentation
site_url: https://grupodiana.github.io/BRT-Documentation/
site_author: Diana Research Group - University of Malaga
site_description: Documentation site of the entire BRT ecosystem

theme:
  name: material
  features:
  - navigation.indexes
  #- navigation.sections
  - navigation.tabs  
  - navigation.top  
  - navigation.tracking
  - navigation.path  
  - toc.integrate
  - toc.follow
  - search.suggest
  - search.highlight
  - content.tabs.link
  - content.code.annotation
  - content.code.copy
  logo: assets/SONICOMwave.png
  favicon: assets/SONICOMwave.png
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: pink
      accent: green
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: pink
      accent: lime

markdown_extensions:
  - toc:
      toc_depth: 3
  - pymdownx.tabbed
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

copyright: 
  Copyright &copy; 2024 <a href="https://www.diana.uma.es/" target="_blank" rel="noopener"> Diana Research Group</a>

# Page tree
nav:
  - Home: index.md
  - BRT Library: 
    - library/index.md
    
    - Source Models: 
      - library/source-models/index.md
      - Simple Model: library/source-models/simpleModel.md
      - Directivity Model: library/sousource-modelsrce/directivityModel.md
      - Virtual Source: library/source-models/virtualSource.md
    - Listener Models: 
      - library/listener-models/index.md
    - Environment Models:
      - library/environment-models/index.md
      - RIR models: 
        - Overview: library/environment-models/rirModels.md
        - Direct BRIR: library/environment-models/directBRIR.md
        - Ambisonic BRIR: library/environment-models/ambisonicBRIR.md 
      - Virtual Sources: library/environment-models/virtualSources.md
    - Binaural Filters:
      - library/binaural-filters/index.md
    - Services Modules: 
      - library/services-modules/index.md      
    - Readers: 
      - library/readers/index.md        
    - Common:
      - library/common/index.md
    - Base:
      - library/base/index.md
    - Connectivity: 
      - library/connectivity/index.md
      
  - Applications: 
    - applications/index.md
    - BeRTA Rendeder: 
      - applications/berta-renderer/index.md
      - Settings File: applications/berta-renderer/settingsFile.md
    - BeRTA GUI: applications/berta-gui.md
    - OSC commands: 
      - Overview: osc/index.md
      - Control commands: osc/control.md
      - Overall commands: osc/overall.md
      - Resources commands: osc/resources.md
      - Source commands: osc/source.md
      - Listener commands: osc/listener.md
      - Environment commands: osc/environment.md
  
  - Examples: 
    - Code blocks: example-code.md    
    - Icons: example-emoji.md
  
  - Setup:
    - setup/index.md
    - Installation: setup/installation.md
      
  - Tutorials:
      - tutorials/index.md
      - "Integration":
        - tutorials/tutorial1/basic.md        
